name: Run tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: |
        mkdir -p build
        cd build
        cmake ..
        cmake --build .

    - name: Test 1
      working-directory: ${{github.workspace}}/build
      run: |
        ./bin/firewall 1 < ../test/packets_1.txt > output.txt
        diff output.txt ../test/expected_output_1.txt
        
    - name: Test 2
      working-directory: ${{github.workspace}}/build
      run: |
        ./bin/firewall 2 < ../test/packets_2.txt > output.txt
        diff output.txt ../test/expected_output_2.txt
        
    - name: Finish
      working-directory: ${{github.workspace}}/build
      run: |
        rm output.txt
        cd ..
        rm -rf build

