name: Run tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build All
      run: |
        mkdir -p build
        cd build
        cmake ..
        cmake --build .
        cd ..

    - name: Test 1st ruleset
      working-directory: ${{github.workspace}}
      run: |
        ./build/bin/firewall 1 < test/packets_1.txt > output.txt
        diff output.txt test/expected_output_1.txt
        
    - name: Test 2nd ruleset
      working-directory: ${{github.workspace}}
      run: |
        ./build/bin/firewall 2 < test/packets_2.txt > output.txt
        diff output.txt test/expected_output_2.txt

    - name: Test 2nd ruleset
      working-directory: ${{github.workspace}}
      run: |
        ./build/bin/rand_pack_gen 20 > random_packets.txt
        ./build/bin/firewall 1 < random_packets.txt

    - name: Finish
      working-directory: ${{github.workspace}}
      run: |
        rm output.txt
        rm random_packets.txt
        cd ..
        rm -rf build

